kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- https://github.com/pingidentity/pingidentity-devops-getting-started/20-kubernetes/03-replicated-pingdirectory

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
    - env_vars.pingdirectory

patchesStrategicMerge:
- limits.yaml
