kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# comment out what you don't want. 
resources:
- pingaccess
- pingfederate
- ../01-standalone/pingdataconsole
- pingdirectory
- pingdatagovernance
- pingdatagovernancepap

# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product
