version: '2.4'
services:
  pingcentral:
    image: pingidentity/pingcentral:${PING_IDENTITY_DEVOPS_TAG}
    container_name: pingcentral
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingcentral/logging
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9022:9022"
