version: "3.1"
# This lauches a simple portainer instance

#-------------------------------------------------------------------------------------
#- Portainer w/ Docker Example
#-
#-                +---------------+
#-                |   Portainer   |
#-                +---------------+
#-
#- To access Portainer Console
#- 
#-    http://localhost:9001/
#-    
#-    Username: admin
#-    Password: (set an inititial password - i.e. 2FederateM0re)
#-
#- First time
#-    After login, select "Local" and then "Connect"
#-------------------------------------------------------------------------------------

services:
  portainer:
    image: portainer/portainer
    command: --logo "https://www.pingidentity.com/content/dam/ping-6-2-assets/topnav-json-configs/Ping-Logo.svg" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    ports:
      - "8001:8000"
      - "9001:9000"

volumes:
  portainer_data: