kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base
#
# Use clusterIP version if using a single external LoadBalancer (current default)
# Use loadBalancer version if using multiple LoadBalancers (i.e. on load balancer per pod)
#
- pingdirectory-service-clusterip.yaml
#- pingdirectory-service-loadbalancer.yaml

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
    - env_vars.pingdirectory

