version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingdatagovernance:
    image: pingidentity/pingdatagovernance:${PING_IDENTITY_DEVOPS_TAG}
    environment: 
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernance
      - SERVER_PROFILE_PARENT=PDG
      - SERVER_PROFILE_PDG_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PDG_PATH=baseline/pingdatagovernance
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file: 
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdatagovernance:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdatagovernance:/opt/in
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8080:80"
      - "7443:443"
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdatagovernancepap:
    image: pingidentity/pingdatagovernancepap:${PING_IDENTITY_DEVOPS_TAG}
    environment: 
    #  - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
    #  - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernancepap
      - PING_IDENTITY_ACCEPT_EULA=YES
      - HTTPS_PORT=8443
    env_file: 
      - ~/.pingidentity/devops
    volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdatagovernancepap:/opt/out
       - ${HOME}/projects/devops/pingidentity-server-profiles/pdg-pap-integration/pingdatagovernancepap:/opt/in
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8443:8443"
    networks:
      - pingnet-dmz

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_ACCEPT_EULA=YES
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
